### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-sandrapinazo#1]
Good job @sandrapinazo  !!!

Here you have some tips to improve the exercise:

- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Do not forget to add units (px, rem, %) of width and height.
- [x] Remove `,` when using `padding` or `margin` shortcuts.
- [ ] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Finish the main title styles: words should jump and the typography is smaller and bolder
- [x] Finish the menu styles: blog and contact should be separated.
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

Once you have these fixed add the tablet styles, step by step

Let me know if you have any doubts ;)

Go for it!!

**Comment by sandrapinazo** [comment]
Thanks @nasivuela!

I tried to solve all the issues and added responsive for tablet.

I have a doubt about the width: 100% or 100vw issue. I only have width: 100% in the header styles, and if I remove them the header doesn't cover the full length, and a height: 100vh that makes the main element full height. Am I missing something?

**Comment by nasivuela** [comment]
@sandrapinazo You are right about the width, my mistake sorry. 
If you want to make it perfect, there is a little detail on `Diversidad` word on the tablet, it looks slightly moved to the right, maybe because of the width?

Anyway, it looks super to me, well done!!

![](https://media.giphy.com/media/4Zo41lhzKt6iZ8xff9/giphy.gif)
